---
title: "Chapter 1"
format: html
toc: true
editor: visual
editor_options: 
  chunk_output_type: console
---

We first introduce the type of sample, or data, required for each of the analyses presented in this part. We then discuss winsorization, a technique that is used to adjust data, in order to minimize the effect of outliers on statistical analyses. Finally, we explain Newey and West (1987)-adjusted standard errors, t-statistics, and p-values, which are commonly used to avoid problems with statistical inference associated with heteroscedasticity and autocorrelation in time-series data.

### Methodologies Sample

The sample covers a period of 25 years from 1988 through 2012 inclusive. For each year $t$, the sample includes all stocks $i$ in the Center for Research in Security Prices (CRSP) database that are listed as U.S.-based common stocks on December 31 of the year $t$.

### Outliers

-   winsorization: sets the values of a given variable that are above or below a certain cutoff to that cutoff.
-   truncation: takes values of a given variable that are deemed extreme to be missing.

implemetation:

-   winsorize or truncate using all values of the given variable X over all entities i and time periods t.
-   winsorize or truncate X separately for each time period t.

### Newey&West SE Adjustment

-   to account for the impact of autocorrelation and heteroscedasticity
